**By:** *Ahmed Sharaf*

In this notebook you will practice how to:
1. Calculate the determinant of a 2x2 matrix with and without using numpy.linalg
2. Calculate the determinant of a 3x3 matrix with and without using numpy.linalg
3. Calculate the inverse of a 2x2 matrix using numpy.linalg
4. Calculate the inverse of a 3x3 matrix using numpy.linalg
5. Finding the rank of a matrix using numpy

### Notice

**Please Note:**  
When writing code, make sure to place it in the designated area marked with `# code here`.  
If there is a `pass` keyword in the code, please remove it and replace it with the required code.

# Calculating the determinant using numpy.linalg

In [40]:
import numpy as np

In [41]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [42]:
a3 = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(a3)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


In [43]:
## Determinate of a2, a3
det_a2 = np.linalg.det(a2)
print(det_a2)
det_a3 = np.linalg.det(a3)
print(det_a3)

-2.0000000000000004
-7.999999999999998


# Calculating the determinant of a 2x2 matrixwithout using numpy

In [44]:
def Det2(Mat):
    if len(Mat) != 2 or len(Mat[0]) != 2:
        raise ValueError("Input matrix should be 2x2")
    else:
        det = (Mat[0][0] * Mat[1][1]) - (Mat[0][1] * Mat[1][0])
        return det


print(Det2(a2))

-2


# Calculating the determinant of a 3x3 matrixwithout using numpy

One idea
1. write a function to calculate the minor matrices. (hint, use slices)
2. write a function to calculate the cofactors (this should call the first function, and the determinant function)
3. the determinant function calls the function in step two and adds the results together.

Another idea 
use recursion ==> code credit https://stackoverflow.com/questions/3819500/code-to-solve-determinant-using-python-without-using-scipy-linalg-det

In [45]:
# delete function removes a sub-array from the input array
# first argument is the original array
# second argument is the index to the sub-array to be removed
# third argument is the axis among which the deletion happens (0: x axis "row" and 1: y axis "column")
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

arr2 = np.delete(arr, 1, 0)
print(arr2)

arr3 = np.delete(arr, 3, 1)
print(arr3)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
def minor(arr,i,j):
    return np.delete(np.delete(arr, i, 0), j, 1)


def det(arr):
    n = len(arr)
    if n == 2:
        return arr[0, 0] * arr[1, 1] - arr[0, 1] * arr[1, 0]
    
    d = 0
    for j in range(n):
        c = (-1) ** j * arr[0, j] * det(minor(arr, 0, j))
        d += c
    
    return d
    
print(a3)
print(det(a3))

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]
-8


# Calculating the inverse using numpy.linalg

In [54]:
# The inverse of 2 x 2 matrix

a2 = np.array([[1,2],[3,4]])

print(a2)

print(np.linalg.det(a2))
print(np.linalg.inv(a2))

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [63]:
# The inverse of a singular matrix

a3 = np.array([[1,2],[2,4]])

print(a3)
det = np.linalg.det(a3)
print(det)
if int(det) == 0.0 :
    raise ValueError("Singular Matrix cannot be Inverted")
else:
    print(np.linalg.inv(a3))

[[1 2]
 [2 4]]
0.0


ValueError: Singular Matrix cannot be Inverted

In [64]:
# The inverse of 3 x 3 matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.det(A))
print(np.linalg.inv(A))

-306.0
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [65]:
# Inverses of several matrices can
# be computed at once

A = np.array([[[1., 2.], 
               [3., 4.]],
              [[1, 3], 
               [3, 5]]])
  
# Calculating the inverse of the matrix
print(np.linalg.det(A))
print(np.linalg.inv(A))

[-2. -4.]
[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]


# Calculating the inverse of a 2x2 matrixwithout using numpy

1. Code a function to calculate the determinant of 2x2 matrix
2. Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements
3. Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists

In [72]:
#step -1- we already coded the det function that works for 2x2 and nxn size matrix
def det(arr):
    n = len(arr)
    if n == 2:
        return arr[0, 0] * arr[1, 1] - arr[0, 1] * arr[1, 0]
    
    d = 0
    for j in range(n):
        c = (-1) ** j * arr[0, j] * det(minor(arr, 0, j))
        d += c
    
    return d


#step -2-
def interchangeMatrix(A):
   A[0, 0], A[1, 1] = A[1, 1], A[0, 0]
   
   A[0, 1] = -A[0, 1]
   A[1, 0] = -A[1, 0]
   
   return A


#step -3-
def inverse2x2(A):
    return 1/det(A) * interchangeMatrix(A)

a2 = np.array([[1,2],[3,4]])
print(inverse2x2(a2))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Calculating the inverse of a 3x3 matrixwithout using numpy

# Use the adjoint matrix method

Coding a Python code to inverse a 3x3 matrix (no numpy.linalg.inv allowed):
1. Coding a function that checks if a 3x3 matrix is invertible
2. Coding a function that generates the transpose of a 3x3 matrix
3. Coding a function that generates the matrix of minors of a 3x3 matrix
4. Coding a function that generates the matrix of cofactors of a 3x3 matrix
5. Coding a function that generates the inverse of a 3x3 matrix if it exists


In [76]:
#step -1- a matrix is invertible only if its determinant != 0
def invertible(A):
    return det(A) != 0

#step -2- rows and columns could be interchanged without the need of built-in methods
def transposeM(A):
    return np.array([[A[j, i] for j in range(len(A))] for i in range(len(A[0]))])

#step -3- we coded that previously minor(arr,i,j)
def minor(arr,i,j):
    return np.delete(np.delete(arr, i, 0), j, 1)

#step -4- Calculating the matrix of cofactors (minors determinants multiplied by signs)
def cofactors(A):
    n = len(A)
    cofactor_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor_matrix = minor(A, i, j)
            cofactor_matrix[i, j] = ((-1) ** (i + j)) * det(minor_matrix)
    return cofactor_matrix


#step -5- Inverse is the transpose of the cofactor matrix divided by the determinant of the original/input matrix
def inverse3x3(A):
    if not invertible(A):
        raise ValueError("Matrix not invertible det = 0")
    
    cofactor_m = cofactors(A)
    
    adj_m = transposeM(cofactor_m)
    
    inverse_m = adj_m / det(A)
    
    return inverse_m


B = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(inverse3x3(B))

#[ 0.17647059 -0.00326797 -0.02287582]
# [ 0.05882353 -0.13071895  0.08496732]
# [-0.11764706  0.1503268   0.05228758]]
#check
print(np.linalg.inv(B))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


# Finding the rank of a matrix using numpy

In [78]:
a3 = np.array([[1,2],[2,4]])

print(np.linalg.matrix_rank(a3))

1
